### ISSUE TITLE
pro run doesn't run any command

### ISSUE THREAD

**Issue by Haroenv** [trishume/pro#24]
When running `pro run`, the following error is generated
```
/usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/commands.rb:59:in ``': No such file or directory - branch (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/commands.rb:59:in `block in run_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/index.rb:13:in `block (2 levels) in each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/index.rb:13:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/index.rb:13:in `block in each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/index.rb:12:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/index.rb:12:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/lib/pro/commands.rb:57:in `run_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/pro-1.1.5/bin/pro:90:in `<top (required)>'
	from /usr/local/bin/pro:23:in `load'
	from /usr/local/bin/pro:23:in `<main>'
```

**Comment by Haroenv** [comment]
Never mind, I found that you need to enter `pro run git pull`, and not `pro run pull`. My fault.
